import { Pinecone } from '@pinecone-database/pinecone';

// Phase 4: Vector Store Scaffolding (Pinecone)
export const pinecone = new Pinecone({
  apiKey: process.env.PINECONE_API_KEY || 'dummy-key',
});

// Target index name (must be created in Pinecone dashboard)
export const getVectorStoreIndex = () => pinecone.Index('repo-to-resume');

/**
 * Persists repository embeddings linked to a user's GitHub ID.
 * This avoids re-calculating embeddings on every page refresh.
 */
export async function upsertRepoEmbeddings(githubId: string, reposWithEmbeddings: any[]) {
  if (!process.env.PINECONE_API_KEY) {
    console.warn("PINECONE_API_KEY missing - skipping real upsert.");
    return;
  }
  
  const index = getVectorStoreIndex();
  
  const records = reposWithEmbeddings.map(repo => {
    // Vectorize full repo metrics inside values. 
    // In production, values would be the dimension=768 embedding array generated by Gemini.
    return {
      id: `${githubId}-${repo.name}`,
      values: repo.embedding, 
      metadata: {
        githubId,
        name: repo.name,
        description: repo.description || "",
        // Serialized strings to stay within metadata size limits
        languages: JSON.stringify(Object.keys(repo.languages || {})), 
      }
    };
  });
  await index.upsert(records as any);
}

/**
 * Semantic search against Pinecone for scale. 
 */
export async function queryRepoEmbeddings(githubId: string, queryEmbedding: number[], topK: number = 3) {
  if (!process.env.PINECONE_API_KEY) {
    console.warn("PINECONE_API_KEY missing - skipping real query.");
    return null;
  }
  
  const index = getVectorStoreIndex();
  const results = await index.query({
    vector: queryEmbedding,
    topK,
    filter: { githubId },
    includeMetadata: true
  });
  
  return results.matches;
}
